//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Client_VM_applications = new HashSet<Client_VM_applications>();
            this.Deal = new HashSet<Deal>();
        }
    
        public int cl_id { get; set; }
        public string cl_surname { get; set; }
        public string cl_name { get; set; }
        public string cl_patronymic { get; set; }
        public int a_id { get; set; }
        public string cl_telNum { get; set; }
        public int cs_id { get; set; }
    
        public virtual Address_ Address_ { get; set; }
        public virtual Client_status Client_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_VM_applications> Client_VM_applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
    }
}
