//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_VM_applications
    {
        public int cvma_id { get; set; }
        public string cvma_name { get; set; }
        public int cl_id { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
