//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damage_penalty
    {
        public int dmgp_id { get; set; }
        public int d_id { get; set; }
        public Nullable<double> dmgp_ammount { get; set; }
        public string dmgp_description { get; set; }
    
        public virtual Deal Deal { get; set; }
    }
}
