//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.Damage_penalty = new HashSet<Damage_penalty>();
            this.Delay_penalty = new HashSet<Delay_penalty>();
            this.Video_media = new HashSet<Video_media>();
        }
    
        public int d_id { get; set; }
        public int e_id { get; set; }
        public int cl_id { get; set; }
        public System.DateTime d_tDate { get; set; }
        public Nullable<System.DateTime> d_tCompletionDate { get; set; }
        public Nullable<double> d_cost { get; set; }
        public Nullable<bool> d_isCompleted { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage_penalty> Damage_penalty { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delay_penalty> Delay_penalty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_media> Video_media { get; set; }
    }
}
