//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Deal = new HashSet<Deal>();
            this.Video_media_order = new HashSet<Video_media_order>();
        }
    
        public int e_id { get; set; }
        public string e_surname { get; set; }
        public string e_name { get; set; }
        public string e_patronymic { get; set; }
        public int a_id { get; set; }
        public string e_telNum { get; set; }
        public string e_position { get; set; }
        public Nullable<double> e_salary { get; set; }
    
        public virtual Address_ Address_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_media_order> Video_media_order { get; set; }
    }
}
