//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider_()
        {
            this.Video_media_order = new HashSet<Video_media_order>();
        }
    
        public int p_id { get; set; }
        public string p_title { get; set; }
        public int a_id { get; set; }
        public string p_telNum { get; set; }
        public string p_surname { get; set; }
        public string p_name { get; set; }
        public string p_patronymic { get; set; }
    
        public virtual Address_ Address_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_media_order> Video_media_order { get; set; }
    }
}
