//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        public int u_id { get; set; }
        public string ulogin { get; set; }
        public string upassword { get; set; }
        public byte ut_id { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual User_type User_type { get; set; }
    }
}
