//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_media_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video_media_order()
        {
            this.Video_media = new HashSet<Video_media>();
        }
    
        public int vmo_id { get; set; }
        public System.DateTime vmo_tData { get; set; }
        public Nullable<System.DateTime> vmo_tCompletionDate { get; set; }
        public int p_id { get; set; }
        public int e_id { get; set; }
        public Nullable<bool> vmo_isCompleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Provider_ Provider_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_media> Video_media { get; set; }
    }
}
