//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video_media()
        {
            this.Deal = new HashSet<Deal>();
        }
    
        public int vm_id { get; set; }
        public int c_id { get; set; }
        public Nullable<int> vmo_id { get; set; }
        public int vmt_id { get; set; }
        public Nullable<double> vm_dailyRentPrice { get; set; }
        public Nullable<byte> vm_durability { get; set; }
        public Nullable<double> vm_price { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Video_media_order Video_media_order { get; set; }
        public virtual Video_media_type Video_media_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
    }
}
